version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: job-portal-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: user_db
      SECRET_KEY: SECRET_KEY

  job-service:
    build: ./job-service
    container_name: job-service
    ports:
      - "3002:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: job_db
      SECRET_KEY: SECRET_KEY

  application-service:
    build: ./application-service
    container_name: application-service
    ports:
      - "3003:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: application_db
      SECRET_KEY: SECRET_KEY

volumes:
  postgres_data: