version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: job-portal-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  user-service:
    build:
      context: ./user-service
      target: test
    container_name: user-service-test
    depends_on:
      - postgres
    environment:
      NODE_ENV: test
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: user_test_db
      SECRET_KEY: TEST_SECRET

  job-service:
    build:
      context: ./job-service
      target: test
    container_name: job-service-test
    depends_on:
      - postgres
    environment:
      NODE_ENV: test
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: job_test_db
      SECRET_KEY: TEST_SECRET

  application-service:
    build:
      context: ./application-service
      target: test
    container_name: application-service-test
    depends_on:
      - postgres
    environment:
      NODE_ENV: test
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: application_test_db
      SECRET_KEY: TEST_SECRET
      JOB_SERVICE_HOST: job-service:3000
