apiVersion: v1
kind: ConfigMap
metadata:
  name: job-portal-config
  namespace: job-portal
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USERNAME: "postgres"
  PORT: "3000"
  JOB_SERVICE_HOST: "job-service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: job-portal
data:
  init.sql: |
    CREATE DATABASE user_db;
    CREATE DATABASE job_db;
    CREATE DATABASE application_db;
